/**
 * GitHub Path Generation Utilities
 * Automatic githubPath generation for documents
 */

import { prisma } from '@/lib/prisma';
import slugify from 'slugify';

export interface GenerateGitHubPathOptions {
  phase: string;
  type: string;
  title: string;
  workspaceId: string;
}

/**
 * Generate a unique GitHub path for a document
 * Format: ${slugify(phase)}/${slugify(type)}/${slugify(title)}.md
 *
 * If a duplicate exists in the same workspace, appends -2, -3, etc.
 */
export async function generateUniqueGitHubPath(
  options: GenerateGitHubPathOptions
): Promise<string> {
  const { phase, type, title, workspaceId } = options;

  // Slugify each component
  const phaseSlug = slugify(phase, {
    lower: true,
    strict: true,
    remove: /[*+~.()'"!:@]/g,
  });

  const typeSlug = slugify(type, {
    lower: true,
    strict: true,
    remove: /[*+~.()'"!:@]/g,
  });

  const titleSlug = slugify(title, {
    lower: true,
    strict: true,
    remove: /[*+~.()'"!:@]/g,
  });

  // Generate base path
  const basePath = `${phaseSlug}/${typeSlug}/${titleSlug}.md`;

  // Check if this path already exists in the workspace
  const existingDoc = await prisma.document.findFirst({
    where: {
      workspaceId,
      githubPath: basePath,
    },
  });

  // If no conflict, return base path
  if (!existingDoc) {
    return basePath;
  }

  // If conflict exists, find a unique suffix
  let suffix = 2;
  let uniquePath = `${phaseSlug}/${typeSlug}/${titleSlug}-${suffix}.md`;

  while (true) {
    const conflictDoc = await prisma.document.findFirst({
      where: {
        workspaceId,
        githubPath: uniquePath,
      },
    });

    if (!conflictDoc) {
      return uniquePath;
    }

    suffix++;
    uniquePath = `${phaseSlug}/${typeSlug}/${titleSlug}-${suffix}.md`;
  }
}

/**
 * Update githubPath for an existing document
 */
export async function updateDocumentGitHubPath(
  documentId: string,
  options: Omit<GenerateGitHubPathOptions, 'workspaceId'>
): Promise<string> {
  const document = await prisma.document.findUnique({
    where: { id: documentId },
    select: { workspaceId: true },
  });

  if (!document) {
    throw new Error('Document not found');
  }

  const githubPath = await generateUniqueGitHubPath({
    ...options,
    workspaceId: document.workspaceId,
  });

  await prisma.document.update({
    where: { id: documentId },
    data: {
      githubPath,
      githubAutoGenerated: true,
    },
  });

  return githubPath;
}
