/**
 * GitHub Path Generation Utilities
 * Automatic githubPath generation for documents
 */

import { prisma } from '@/lib/prisma';
import slugify from 'slugify';

export interface GenerateGitHubPathOptions {
  phase: string;
  type: string;
  title: string;
  workspaceId: string;
}

/**
 * Check if a path points to a markdown-like file.
 */
export function isMarkdownPath(path: string): boolean {
  return /\.(md|markdown|mdx)$/i.test(path);
}

/**
 * Derive a document title from a markdown path.
 * Examples:
 * - docs/planning/test-workspace-beta.md -> test-workspace-beta
 * - README.md -> README
 */
export function deriveTitleFromMarkdownPath(markdownPath: string): string {
  const normalized = markdownPath.replace(/^\/+/, '');
  const filename = normalized.split('/').pop() || normalized;
  const title = filename.replace(/\.(md|markdown|mdx)$/i, '').trim();
  return title || 'Imported Document';
}

/**
 * Generate a unique GitHub path for a document
 * Format: ${slugify(phase)}/${slugify(type)}/${slugify(title)}.md
 *
 * If a duplicate exists in the same workspace, appends -2, -3, etc.
 */
export async function generateUniqueGitHubPath(
  options: GenerateGitHubPathOptions
): Promise<string> {
  const { phase, type, title, workspaceId } = options;

  // Slugify each component
  const phaseSlug = slugify(phase, {
    lower: true,
    strict: true,
    remove: /[*+~.()'"!:@]/g,
  });

  const typeSlug = slugify(type, {
    lower: true,
    strict: true,
    remove: /[*+~.()'"!:@]/g,
  });

  const titleSlug = slugify(title, {
    lower: true,
    strict: true,
    remove: /[*+~.()'"!:@]/g,
  });

  // Generate base path
  const basePath = `${phaseSlug}/${typeSlug}/${titleSlug}.md`;

  // Check if this path already exists in the workspace
  const existingDoc = await prisma.document.findFirst({
    where: {
      workspaceId,
      githubPath: basePath,
    },
  });

  // If no conflict, return base path
  if (!existingDoc) {
    return basePath;
  }

  // If conflict exists, find a unique suffix
  let suffix = 2;
  let uniquePath = `${phaseSlug}/${typeSlug}/${titleSlug}-${suffix}.md`;

  while (true) {
    const conflictDoc = await prisma.document.findFirst({
      where: {
        workspaceId,
        githubPath: uniquePath,
      },
    });

    if (!conflictDoc) {
      return uniquePath;
    }

    suffix++;
    uniquePath = `${phaseSlug}/${typeSlug}/${titleSlug}-${suffix}.md`;
  }
}

/**
 * Convert a custom document path to a GitHub file path.
 * Strips leading slash, appends .md extension.
 * e.g. /onboarding/sop -> onboarding/sop.md
 */
export function githubPathFromCustomPath(customPath: string): string {
  const stripped = customPath.replace(/^\/+/, '').replace(/\/+$/, '');
  if (!stripped) return 'documents/untitled.md';
  if (/\.(md|markdown|mdx)$/i.test(stripped)) return stripped;
  return `${stripped}.md`;
}

/**
 * Generate a unique GitHub file path derived from a custom document path.
 * Appends -2, -3, ... suffix before the extension if conflicts exist.
 */
export async function generateUniqueGitHubPathFromCustom(
  customPath: string,
  workspaceId: string,
  excludeDocumentId?: string
): Promise<string> {
  const base = githubPathFromCustomPath(customPath);
  const withoutExt = base.replace(/\.md$/, '');

  const existingDoc = await prisma.document.findFirst({
    where: {
      workspaceId,
      githubPath: base,
      ...(excludeDocumentId ? { id: { not: excludeDocumentId } } : {}),
    },
  });

  if (!existingDoc) return base;

  let suffix = 2;
  while (true) {
    const uniquePath = `${withoutExt}-${suffix}.md`;
    const conflict = await prisma.document.findFirst({
      where: {
        workspaceId,
        githubPath: uniquePath,
        ...(excludeDocumentId ? { id: { not: excludeDocumentId } } : {}),
      },
    });
    if (!conflict) return uniquePath;
    suffix++;
  }
}

/**
 * Update githubPath for an existing document
 */
export async function updateDocumentGitHubPath(
  documentId: string,
  options: Omit<GenerateGitHubPathOptions, 'workspaceId'>
): Promise<string> {
  const document = await prisma.document.findUnique({
    where: { id: documentId },
    select: { workspaceId: true },
  });

  if (!document) {
    throw new Error('Document not found');
  }

  const githubPath = await generateUniqueGitHubPath({
    ...options,
    workspaceId: document.workspaceId,
  });

  await prisma.document.update({
    where: { id: documentId },
    data: {
      githubPath,
      githubAutoGenerated: true,
    },
  });

  return githubPath;
}
