-- CreateEnum
CREATE TYPE "WorkspaceInviteStatus" AS ENUM ('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED');

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "ActivityType" ADD VALUE 'GITHUB_REPO_CONNECTED';
ALTER TYPE "ActivityType" ADD VALUE 'GITHUB_REPO_DISCONNECTED';
ALTER TYPE "ActivityType" ADD VALUE 'GITHUB_SYNC_STARTED';
ALTER TYPE "ActivityType" ADD VALUE 'GITHUB_SYNC_SUCCESS';
ALTER TYPE "ActivityType" ADD VALUE 'GITHUB_SYNC_FAILED';
ALTER TYPE "ActivityType" ADD VALUE 'GITHUB_CONFLICT_DETECTED';
ALTER TYPE "ActivityType" ADD VALUE 'GITHUB_PULL_REQUEST_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'WORKSPACE_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'WORKSPACE_DELETED';
ALTER TYPE "ActivityType" ADD VALUE 'OWNERSHIP_TRANSFERRED';
ALTER TYPE "ActivityType" ADD VALUE 'MEMBER_INVITED';
ALTER TYPE "ActivityType" ADD VALUE 'INVITE_ACCEPTED';
ALTER TYPE "ActivityType" ADD VALUE 'INVITE_REJECTED';
ALTER TYPE "ActivityType" ADD VALUE 'PASSWORD_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE 'ACCOUNT_DELETED';
ALTER TYPE "ActivityType" ADD VALUE 'GITHUB_IMPORT';
ALTER TYPE "ActivityType" ADD VALUE 'GITHUB_EXPORT';

-- DropForeignKey
ALTER TABLE "Workspace" DROP CONSTRAINT "Workspace_ownerId_fkey";

-- AlterTable
ALTER TABLE "DocSyncInfo" ADD COLUMN     "lastCommitSha" TEXT,
ADD COLUMN     "lastCommitUrl" TEXT;

-- AlterTable
ALTER TABLE "Document" ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "githubAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "githubPath" TEXT,
ADD COLUMN     "githubSha" TEXT;

-- AlterTable
ALTER TABLE "GitHubPullRequest" ADD COLUMN     "affectedFiles" TEXT[],
ADD COLUMN     "autoCreated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "linkedDocumentIds" TEXT[];

-- AlterTable
ALTER TABLE "GitHubRepo" ADD COLUMN     "autoCreatePR" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "autoSyncOnSave" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "defaultCommitMessage" TEXT NOT NULL DEFAULT 'docs: update documentation',
ADD COLUMN     "hasWriteAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "prTemplate" TEXT,
ADD COLUMN     "syncDebounceMs" INTEGER NOT NULL DEFAULT 5000,
ADD COLUMN     "syncMode" TEXT NOT NULL DEFAULT 'direct',
ADD COLUMN     "webhookId" TEXT,
ADD COLUMN     "webhookSecret" TEXT;

-- AlterTable
ALTER TABLE "SyncEvent" ADD COLUMN     "commitSha" TEXT,
ADD COLUMN     "documentId" TEXT,
ADD COLUMN     "prId" TEXT,
ADD COLUMN     "prNumber" INTEGER;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "githubAvatarUrl" TEXT,
ADD COLUMN     "githubEmail" TEXT,
ADD COLUMN     "githubProfileUrl" TEXT,
ADD COLUMN     "githubTokenExpiresAt" TIMESTAMP(3),
ADD COLUMN     "githubTokenScopes" TEXT[],
ADD COLUMN     "githubUserId" INTEGER,
ADD COLUMN     "githubUsername" TEXT;

-- CreateTable
CREATE TABLE "WorkspaceGitHubIntegration" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "repository" TEXT NOT NULL,
    "branch" TEXT NOT NULL DEFAULT 'main',
    "basePath" TEXT NOT NULL DEFAULT 'docs',
    "webhookSecret" TEXT,
    "webhookId" TEXT,
    "webhookUrl" TEXT,
    "webhookActive" BOOLEAN NOT NULL DEFAULT true,
    "webhookCreatedAt" TIMESTAMP(3),
    "webhookUpdatedAt" TIMESTAMP(3),
    "connectedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WorkspaceGitHubIntegration_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SyncQueue" (
    "id" TEXT NOT NULL,
    "documentId" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "operation" TEXT NOT NULL,
    "priority" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "attemptCount" INTEGER NOT NULL DEFAULT 0,
    "maxAttempts" INTEGER NOT NULL DEFAULT 3,
    "error" TEXT,
    "metadata" JSONB,
    "scheduledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "startedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "repoId" TEXT,

    CONSTRAINT "SyncQueue_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GitHubWebhook" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "repoId" TEXT NOT NULL,
    "githubWebhookId" TEXT NOT NULL,
    "secret" TEXT NOT NULL,
    "events" TEXT[],
    "active" BOOLEAN NOT NULL DEFAULT true,
    "lastDeliveryAt" TIMESTAMP(3),
    "lastStatus" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GitHubWebhook_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ConflictResolution" (
    "id" TEXT NOT NULL,
    "documentId" TEXT NOT NULL,
    "syncInfoId" TEXT NOT NULL,
    "localContent" TEXT NOT NULL,
    "remoteContent" TEXT NOT NULL,
    "localSha" TEXT NOT NULL,
    "remoteSha" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "resolution" TEXT,
    "resolvedBy" TEXT,
    "resolvedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ConflictResolution_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UploadedImage" (
    "id" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "size" INTEGER NOT NULL,
    "contentType" TEXT NOT NULL,
    "hash" TEXT NOT NULL,
    "uploadedBy" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UploadedImage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WorkspaceInvite" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "invitedEmail" TEXT,
    "invitedUserId" TEXT,
    "invitedById" TEXT NOT NULL,
    "status" "WorkspaceInviteStatus" NOT NULL DEFAULT 'PENDING',
    "message" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "expiresAt" TIMESTAMP(3),
    "acceptedAt" TIMESTAMP(3),
    "rejectedAt" TIMESTAMP(3),

    CONSTRAINT "WorkspaceInvite_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "WorkspaceGitHubIntegration_workspaceId_key" ON "WorkspaceGitHubIntegration"("workspaceId");

-- CreateIndex
CREATE INDEX "WorkspaceGitHubIntegration_repository_idx" ON "WorkspaceGitHubIntegration"("repository");

-- CreateIndex
CREATE INDEX "WorkspaceGitHubIntegration_webhookId_idx" ON "WorkspaceGitHubIntegration"("webhookId");

-- CreateIndex
CREATE INDEX "SyncQueue_status_priority_idx" ON "SyncQueue"("status", "priority" DESC);

-- CreateIndex
CREATE INDEX "SyncQueue_documentId_idx" ON "SyncQueue"("documentId");

-- CreateIndex
CREATE INDEX "SyncQueue_workspaceId_idx" ON "SyncQueue"("workspaceId");

-- CreateIndex
CREATE INDEX "SyncQueue_scheduledAt_idx" ON "SyncQueue"("scheduledAt");

-- CreateIndex
CREATE UNIQUE INDEX "GitHubWebhook_githubWebhookId_key" ON "GitHubWebhook"("githubWebhookId");

-- CreateIndex
CREATE INDEX "GitHubWebhook_repoId_idx" ON "GitHubWebhook"("repoId");

-- CreateIndex
CREATE INDEX "GitHubWebhook_workspaceId_idx" ON "GitHubWebhook"("workspaceId");

-- CreateIndex
CREATE INDEX "ConflictResolution_documentId_idx" ON "ConflictResolution"("documentId");

-- CreateIndex
CREATE INDEX "ConflictResolution_status_idx" ON "ConflictResolution"("status");

-- CreateIndex
CREATE INDEX "ConflictResolution_createdAt_idx" ON "ConflictResolution"("createdAt");

-- CreateIndex
CREATE INDEX "UploadedImage_workspaceId_idx" ON "UploadedImage"("workspaceId");

-- CreateIndex
CREATE INDEX "UploadedImage_uploadedBy_idx" ON "UploadedImage"("uploadedBy");

-- CreateIndex
CREATE INDEX "UploadedImage_createdAt_idx" ON "UploadedImage"("createdAt");

-- CreateIndex
CREATE INDEX "UploadedImage_hash_idx" ON "UploadedImage"("hash");

-- CreateIndex
CREATE UNIQUE INDEX "UploadedImage_workspaceId_hash_key" ON "UploadedImage"("workspaceId", "hash");

-- CreateIndex
CREATE INDEX "WorkspaceInvite_workspaceId_idx" ON "WorkspaceInvite"("workspaceId");

-- CreateIndex
CREATE INDEX "WorkspaceInvite_invitedEmail_idx" ON "WorkspaceInvite"("invitedEmail");

-- CreateIndex
CREATE INDEX "WorkspaceInvite_invitedUserId_idx" ON "WorkspaceInvite"("invitedUserId");

-- CreateIndex
CREATE INDEX "WorkspaceInvite_invitedById_idx" ON "WorkspaceInvite"("invitedById");

-- CreateIndex
CREATE INDEX "WorkspaceInvite_status_idx" ON "WorkspaceInvite"("status");

-- CreateIndex
CREATE INDEX "WorkspaceInvite_createdAt_idx" ON "WorkspaceInvite"("createdAt");

-- CreateIndex
CREATE INDEX "Activity_createdAt_idx" ON "Activity"("createdAt");

-- CreateIndex
CREATE INDEX "Activity_type_idx" ON "Activity"("type");

-- CreateIndex
CREATE INDEX "Comment_documentId_resolved_idx" ON "Comment"("documentId", "resolved");

-- CreateIndex
CREATE INDEX "Comment_resolved_idx" ON "Comment"("resolved");

-- CreateIndex
CREATE INDEX "Document_githubPath_idx" ON "Document"("githubPath");

-- CreateIndex
CREATE INDEX "Document_deletedAt_idx" ON "Document"("deletedAt");

-- CreateIndex
CREATE INDEX "DocumentTemplate_usageCount_idx" ON "DocumentTemplate"("usageCount");

-- CreateIndex
CREATE INDEX "DocumentTemplate_category_isPublic_idx" ON "DocumentTemplate"("category", "isPublic");

-- CreateIndex
CREATE INDEX "Feedback_status_priority_idx" ON "Feedback"("status", "priority");

-- CreateIndex
CREATE INDEX "Feedback_priority_idx" ON "Feedback"("priority");

-- CreateIndex
CREATE INDEX "GitHubIssue_state_idx" ON "GitHubIssue"("state");

-- CreateIndex
CREATE INDEX "GitHubIssue_createdAt_idx" ON "GitHubIssue"("createdAt");

-- CreateIndex
CREATE INDEX "GitHubPullRequest_linkedDocumentIds_idx" ON "GitHubPullRequest"("linkedDocumentIds");

-- CreateIndex
CREATE INDEX "GitHubPullRequest_state_idx" ON "GitHubPullRequest"("state");

-- CreateIndex
CREATE INDEX "GitHubPullRequest_createdAt_idx" ON "GitHubPullRequest"("createdAt");

-- CreateIndex
CREATE INDEX "InlineComment_documentId_resolved_idx" ON "InlineComment"("documentId", "resolved");

-- CreateIndex
CREATE INDEX "InlineComment_createdAt_idx" ON "InlineComment"("createdAt");

-- CreateIndex
CREATE INDEX "SyncEvent_documentId_idx" ON "SyncEvent"("documentId");

-- CreateIndex
CREATE INDEX "SyncEvent_commitSha_idx" ON "SyncEvent"("commitSha");

-- CreateIndex
CREATE INDEX "SyncEvent_prNumber_idx" ON "SyncEvent"("prNumber");

-- CreateIndex
CREATE INDEX "User_githubUserId_idx" ON "User"("githubUserId");

-- CreateIndex
CREATE INDEX "User_githubUsername_idx" ON "User"("githubUsername");

-- AddForeignKey
ALTER TABLE "Workspace" ADD CONSTRAINT "Workspace_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkspaceGitHubIntegration" ADD CONSTRAINT "WorkspaceGitHubIntegration_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SyncEvent" ADD CONSTRAINT "SyncEvent_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SyncEvent" ADD CONSTRAINT "SyncEvent_prId_fkey" FOREIGN KEY ("prId") REFERENCES "GitHubPullRequest"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SyncQueue" ADD CONSTRAINT "SyncQueue_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SyncQueue" ADD CONSTRAINT "SyncQueue_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SyncQueue" ADD CONSTRAINT "SyncQueue_repoId_fkey" FOREIGN KEY ("repoId") REFERENCES "GitHubRepo"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GitHubWebhook" ADD CONSTRAINT "GitHubWebhook_repoId_fkey" FOREIGN KEY ("repoId") REFERENCES "GitHubRepo"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GitHubWebhook" ADD CONSTRAINT "GitHubWebhook_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConflictResolution" ADD CONSTRAINT "ConflictResolution_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConflictResolution" ADD CONSTRAINT "ConflictResolution_syncInfoId_fkey" FOREIGN KEY ("syncInfoId") REFERENCES "DocSyncInfo"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConflictResolution" ADD CONSTRAINT "ConflictResolution_resolvedBy_fkey" FOREIGN KEY ("resolvedBy") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UploadedImage" ADD CONSTRAINT "UploadedImage_uploadedBy_fkey" FOREIGN KEY ("uploadedBy") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UploadedImage" ADD CONSTRAINT "UploadedImage_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkspaceInvite" ADD CONSTRAINT "WorkspaceInvite_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkspaceInvite" ADD CONSTRAINT "WorkspaceInvite_invitedById_fkey" FOREIGN KEY ("invitedById") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WorkspaceInvite" ADD CONSTRAINT "WorkspaceInvite_invitedUserId_fkey" FOREIGN KEY ("invitedUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
