/**
 * Quick API Test Script
 * Tests that all GitHub integration endpoints are accessible
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function testAPIs() {
  console.log('🧪 Testing GitHub Integration APIs\n');
  console.log('==================================================');

  try {
    // Test 1: Check Prisma client has all models
    console.log('\n✅ Test 1: Prisma Models');
    console.log('  - User model:', typeof prisma.user);
    console.log('  - Document model:', typeof prisma.document);
    console.log('  - ConflictResolution model:', typeof prisma.conflictResolution);
    console.log('  - SyncQueue model:', typeof prisma.syncQueue);
    console.log('  - GitHubWebhook model:', typeof prisma.gitHubWebhook);
    console.log('  - SyncEvent model:', typeof prisma.syncEvent);
    console.log('  - DocSyncInfo model:', typeof prisma.docSyncInfo);

    // Test 2: Verify database connectivity
    console.log('\n✅ Test 2: Database Connectivity');
    const userCount = await prisma.user.count();
    const documentCount = await prisma.document.count();
    const conflictCount = await prisma.conflictResolution.count();
    console.log(`  - Users: ${userCount}`);
    console.log(`  - Documents: ${documentCount}`);
    console.log(`  - Conflicts: ${conflictCount}`);

    // Test 3: Check GitHub-enhanced fields are accessible
    console.log('\n✅ Test 3: GitHub Enhanced Fields');
    const documentWithGithubFields = await prisma.document.findFirst({
      select: {
        id: true,
        githubPath: true,
        githubSha: true,
        githubAutoGenerated: true,
      },
    });
    console.log('  - githubPath field:', documentWithGithubFields !== null || 'accessible');
    console.log('  - githubSha field:', documentWithGithubFields !== null || 'accessible');
    console.log(
      '  - githubAutoGenerated field:',
      documentWithGithubFields !== null || 'accessible'
    );

    // Test 4: Verify relations work
    console.log('\n✅ Test 4: Model Relations');
    const documentWithRelations = await prisma.document.findFirst({
      include: {
        syncInfo: true,
        conflicts: true,
        syncQueue: true,
        syncEvents: true,
      },
    });
    console.log('  - syncInfo relation:', documentWithRelations !== null || 'accessible');
    console.log('  - conflicts relation:', documentWithRelations !== null || 'accessible');
    console.log('  - syncQueue relation:', documentWithRelations !== null || 'accessible');
    console.log('  - syncEvents relation:', documentWithRelations !== null || 'accessible');

    // Test 5: Test conflict resolution model
    console.log('\n✅ Test 5: ConflictResolution Model Operations');
    const conflicts = await prisma.conflictResolution.findMany({
      where: { status: 'pending' },
      take: 5,
    });
    console.log(`  - Can query conflicts: ${conflicts.length} pending conflicts`);

    // Test 6: Test sync queue model
    console.log('\n✅ Test 6: SyncQueue Model Operations');
    const queueItems = await prisma.syncQueue.findMany({
      where: { status: 'pending' },
      take: 5,
    });
    console.log(`  - Can query sync queue: ${queueItems.length} pending items`);

    console.log('\n==================================================');
    console.log('✅ All API tests passed!\n');
  } catch (error) {
    console.error('\n❌ Test failed:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

// Run tests
testAPIs();
