/**
 * GitHub Integration Test Suite
 * Tests all major GitHub integration features
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function testDatabaseSchema() {
  console.log('\n📊 Testing Database Schema...');

  try {
    // Test User GitHub fields
    const userCount = await prisma.user.count();
    console.log(`✅ User model accessible (${userCount} users)`);

    // Test SyncQueue model
    const queueCount = await prisma.syncQueue.count();
    console.log(`✅ SyncQueue model accessible (${queueCount} items)`);

    // Test ConflictResolution model
    const conflictCount = await prisma.conflictResolution.count();
    console.log(`✅ ConflictResolution model accessible (${conflictCount} conflicts)`);

    // Test GitHubWebhook model
    const webhookCount = await prisma.gitHubWebhook.count();
    console.log(`✅ GitHubWebhook model accessible (${webhookCount} webhooks)`);

    return true;
  } catch (error) {
    console.error('❌ Database schema test failed:', error);
    return false;
  }
}

async function testQueueOperations() {
  console.log('\n🔄 Testing Sync Queue Operations...');

  try {
    // Create a test workspace
    const workspace = await prisma.workspace.findFirst();
    if (!workspace) {
      console.log('⚠️  No workspace found, skipping queue tests');
      return true;
    }

    // Create a test document
    const document = await prisma.document.findFirst({
      where: { workspaceId: workspace.id },
    });

    if (!document) {
      console.log('⚠️  No document found, skipping queue tests');
      return true;
    }

    // Test queue item creation
    const queueItem = await prisma.syncQueue.create({
      data: {
        documentId: document.id,
        workspaceId: workspace.id,
        operation: 'push',
        priority: 0,
        status: 'pending',
        metadata: {},
      },
    });

    console.log(`✅ Created sync queue item: ${queueItem.id}`);

    // Test queue item update
    await prisma.syncQueue.update({
      where: { id: queueItem.id },
      data: {
        status: 'processing',
        attemptCount: { increment: 1 },
      },
    });

    console.log(`✅ Updated sync queue item status`);

    // Clean up
    await prisma.syncQueue.delete({ where: { id: queueItem.id } });
    console.log(`✅ Deleted test queue item`);

    return true;
  } catch (error) {
    console.error('❌ Queue operations test failed:', error);
    return false;
  }
}

async function testConflictResolution() {
  console.log('\n⚔️  Testing Conflict Resolution...');

  try {
    // Find a document with sync info
    const document = await prisma.document.findFirst({
      include: { syncInfo: true },
    });

    if (!document || !document.syncInfo) {
      console.log('⚠️  No document with sync info found, skipping conflict tests');
      return true;
    }

    // Create a test conflict
    const conflict = await prisma.conflictResolution.create({
      data: {
        documentId: document.id,
        syncInfoId: document.syncInfo.id,
        localContent: 'Local version of content',
        remoteContent: 'Remote version of content',
        localSha: 'abc123',
        remoteSha: 'def456',
        status: 'pending',
      },
    });

    console.log(`✅ Created conflict resolution record: ${conflict.id}`);

    // Test conflict update
    await prisma.conflictResolution.update({
      where: { id: conflict.id },
      data: {
        status: 'resolved',
        resolution: 'Merged content',
      },
    });

    console.log(`✅ Updated conflict resolution status`);

    // Clean up
    await prisma.conflictResolution.delete({ where: { id: conflict.id } });
    console.log(`✅ Deleted test conflict`);

    return true;
  } catch (error) {
    console.error('❌ Conflict resolution test failed:', error);
    return false;
  }
}

async function testGitHubFields() {
  console.log('\n🔗 Testing GitHub Field Access...');

  try {
    // Test User GitHub fields
    const user = await prisma.user.findFirst({
      select: {
        id: true,
        githubUserId: true,
        githubUsername: true,
        githubAvatarUrl: true,
        githubTokenScopes: true,
      },
    });

    if (user) {
      console.log(`✅ User GitHub fields accessible`);
    }

    // Test Document GitHub fields
    const document = await prisma.document.findFirst({
      select: {
        id: true,
        githubPath: true,
        githubSha: true,
        githubAutoGenerated: true,
      },
    });

    if (document) {
      console.log(`✅ Document GitHub fields accessible`);
    }

    // Test GitHubPullRequest enhanced fields
    const pr = await prisma.gitHubPullRequest.findFirst({
      select: {
        id: true,
        linkedDocumentIds: true,
        affectedFiles: true,
        autoCreated: true,
      },
    });

    console.log(`✅ GitHub PR enhanced fields accessible`);

    return true;
  } catch (error) {
    console.error('❌ GitHub fields test failed:', error);
    return false;
  }
}

async function runAllTests() {
  console.log('🧪 Starting GitHub Integration Tests\n');
  console.log('='.repeat(50));

  const results = {
    schema: await testDatabaseSchema(),
    queue: await testQueueOperations(),
    conflicts: await testConflictResolution(),
    fields: await testGitHubFields(),
  };

  console.log('\n' + '='.repeat(50));
  console.log('\n📋 Test Results Summary:');
  console.log(`   Database Schema:       ${results.schema ? '✅ PASS' : '❌ FAIL'}`);
  console.log(`   Queue Operations:      ${results.queue ? '✅ PASS' : '❌ FAIL'}`);
  console.log(`   Conflict Resolution:   ${results.conflicts ? '✅ PASS' : '❌ FAIL'}`);
  console.log(`   GitHub Fields:         ${results.fields ? '✅ PASS' : '❌ FAIL'}`);

  const allPassed = Object.values(results).every((r) => r);
  console.log(`\n${allPassed ? '✅ All tests passed!' : '❌ Some tests failed'}\n`);

  await prisma.$disconnect();
  process.exit(allPassed ? 0 : 1);
}

runAllTests();
