-- Migration: Add Full GitHub Integration Support
-- This migration adds comprehensive GitHub integration including:
-- 1. Enhanced GitHub OAuth with full user profile
-- 2. Automated path mapping
-- 3. Pull Request tracking
-- 4. Sync queue system
-- 5. Webhook management

-- Step 1: Add enhanced GitHub profile fields to User model
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "githubUserId" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "githubUsername" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "githubAvatarUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "githubProfileUrl" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "githubEmail" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "githubTokenScopes" TEXT[];
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "githubTokenExpiresAt" TIMESTAMP(3);

-- Create indexes for GitHub user lookup
CREATE INDEX IF NOT EXISTS "User_githubUserId_idx" ON "User"("githubUserId");
CREATE INDEX IF NOT EXISTS "User_githubUsername_idx" ON "User"("githubUsername");

-- Step 2: Add automated path mapping to Document model
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "githubPath" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "githubSha" TEXT;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "githubAutoGenerated" BOOLEAN DEFAULT false;

-- Create index for GitHub path lookup
CREATE INDEX IF NOT EXISTS "Document_githubPath_idx" ON "Document"("githubPath");

-- Step 3: Add PR mode and auto-sync settings to GitHubRepo
ALTER TABLE "GitHubRepo" ADD COLUMN IF NOT EXISTS "syncMode" TEXT DEFAULT 'direct';
ALTER TABLE "GitHubRepo" ADD COLUMN IF NOT EXISTS "autoSyncOnSave" BOOLEAN DEFAULT false;
ALTER TABLE "GitHubRepo" ADD COLUMN IF NOT EXISTS "syncDebounceMs" INTEGER DEFAULT 5000;
ALTER TABLE "GitHubRepo" ADD COLUMN IF NOT EXISTS "defaultCommitMessage" TEXT DEFAULT 'docs: update documentation';
ALTER TABLE "GitHubRepo" ADD COLUMN IF NOT EXISTS "autoCreatePR" BOOLEAN DEFAULT false;
ALTER TABLE "GitHubRepo" ADD COLUMN IF NOT EXISTS "prTemplate" TEXT;
ALTER TABLE "GitHubRepo" ADD COLUMN IF NOT EXISTS "webhookId" TEXT;
ALTER TABLE "GitHubRepo" ADD COLUMN IF NOT EXISTS "webhookSecret" TEXT;
ALTER TABLE "GitHubRepo" ADD COLUMN IF NOT EXISTS "hasWriteAccess" BOOLEAN DEFAULT false;

-- Step 4: Add PR-Document linking to GitHubPullRequest
ALTER TABLE "GitHubPullRequest" ADD COLUMN IF NOT EXISTS "linkedDocumentIds" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "GitHubPullRequest" ADD COLUMN IF NOT EXISTS "affectedFiles" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "GitHubPullRequest" ADD COLUMN IF NOT EXISTS "autoCreated" BOOLEAN DEFAULT false;

-- Create index for linked documents
CREATE INDEX IF NOT EXISTS "GitHubPullRequest_linkedDocumentIds_idx" ON "GitHubPullRequest" USING GIN ("linkedDocumentIds");

-- Step 5: Add document link to SyncEvent for tracking
ALTER TABLE "SyncEvent" ADD COLUMN IF NOT EXISTS "documentId" TEXT;
ALTER TABLE "SyncEvent" ADD COLUMN IF NOT EXISTS "commitSha" TEXT;
ALTER TABLE "SyncEvent" ADD COLUMN IF NOT EXISTS "prNumber" INTEGER;

-- Create foreign key for document if not exists
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'SyncEvent_documentId_fkey'
  ) THEN
    ALTER TABLE "SyncEvent" ADD CONSTRAINT "SyncEvent_documentId_fkey" 
      FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE;
  END IF;
END $$;

-- Create indexes for sync event queries
CREATE INDEX IF NOT EXISTS "SyncEvent_documentId_idx" ON "SyncEvent"("documentId");
CREATE INDEX IF NOT EXISTS "SyncEvent_commitSha_idx" ON "SyncEvent"("commitSha");
CREATE INDEX IF NOT EXISTS "SyncEvent_prNumber_idx" ON "SyncEvent"("prNumber");

-- Step 6: Create SyncQueue table for background processing
CREATE TABLE IF NOT EXISTS "SyncQueue" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "documentId" TEXT NOT NULL,
  "workspaceId" TEXT NOT NULL,
  "operation" TEXT NOT NULL,
  "priority" INTEGER NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "attemptCount" INTEGER NOT NULL DEFAULT 0,
  "maxAttempts" INTEGER NOT NULL DEFAULT 3,
  "error" TEXT,
  "metadata" JSONB,
  "scheduledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "startedAt" TIMESTAMP(3),
  "completedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  
  CONSTRAINT "SyncQueue_documentId_fkey" FOREIGN KEY ("documentId") 
    REFERENCES "Document"("id") ON DELETE CASCADE,
  CONSTRAINT "SyncQueue_workspaceId_fkey" FOREIGN KEY ("workspaceId") 
    REFERENCES "Workspace"("id") ON DELETE CASCADE
);

-- Create indexes for sync queue
CREATE INDEX IF NOT EXISTS "SyncQueue_status_priority_idx" ON "SyncQueue"("status", "priority" DESC);
CREATE INDEX IF NOT EXISTS "SyncQueue_documentId_idx" ON "SyncQueue"("documentId");
CREATE INDEX IF NOT EXISTS "SyncQueue_workspaceId_idx" ON "SyncQueue"("workspaceId");
CREATE INDEX IF NOT EXISTS "SyncQueue_scheduledAt_idx" ON "SyncQueue"("scheduledAt");

-- Step 7: Create GitHubWebhook table for webhook management
CREATE TABLE IF NOT EXISTS "GitHubWebhook" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "workspaceId" TEXT NOT NULL,
  "repoId" TEXT NOT NULL,
  "githubWebhookId" TEXT NOT NULL,
  "secret" TEXT NOT NULL,
  "events" TEXT[] NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "lastDeliveryAt" TIMESTAMP(3),
  "lastStatus" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  
  CONSTRAINT "GitHubWebhook_repoId_fkey" FOREIGN KEY ("repoId") 
    REFERENCES "GitHubRepo"("id") ON DELETE CASCADE,
  CONSTRAINT "GitHubWebhook_workspaceId_fkey" FOREIGN KEY ("workspaceId") 
    REFERENCES "Workspace"("id") ON DELETE CASCADE
);

-- Create indexes for webhook management
CREATE UNIQUE INDEX IF NOT EXISTS "GitHubWebhook_githubWebhookId_key" ON "GitHubWebhook"("githubWebhookId");
CREATE INDEX IF NOT EXISTS "GitHubWebhook_repoId_idx" ON "GitHubWebhook"("repoId");
CREATE INDEX IF NOT EXISTS "GitHubWebhook_workspaceId_idx" ON "GitHubWebhook"("workspaceId");

-- Step 8: Create ConflictResolution table for tracking merge conflicts
CREATE TABLE IF NOT EXISTS "ConflictResolution" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "documentId" TEXT NOT NULL,
  "syncInfoId" TEXT NOT NULL,
  "localContent" TEXT NOT NULL,
  "remoteContent" TEXT NOT NULL,
  "localSha" TEXT NOT NULL,
  "remoteSha" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "resolution" TEXT,
  "resolvedBy" TEXT,
  "resolvedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  
  CONSTRAINT "ConflictResolution_documentId_fkey" FOREIGN KEY ("documentId") 
    REFERENCES "Document"("id") ON DELETE CASCADE,
  CONSTRAINT "ConflictResolution_syncInfoId_fkey" FOREIGN KEY ("syncInfoId") 
    REFERENCES "DocSyncInfo"("id") ON DELETE CASCADE,
  CONSTRAINT "ConflictResolution_resolvedBy_fkey" FOREIGN KEY ("resolvedBy") 
    REFERENCES "User"("id") ON DELETE SET NULL
);

-- Create indexes for conflict resolution
CREATE INDEX IF NOT EXISTS "ConflictResolution_documentId_idx" ON "ConflictResolution"("documentId");
CREATE INDEX IF NOT EXISTS "ConflictResolution_status_idx" ON "ConflictResolution"("status");
CREATE INDEX IF NOT EXISTS "ConflictResolution_createdAt_idx" ON "ConflictResolution"("createdAt");
