import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { ActivityTracker } from '@/lib/activity';
import { z } from 'zod';
import crypto from 'crypto';
import { WORKSPACE_PERMISSION } from '@/lib/workspace-permission-definitions';
import { assertPermission, WorkspacePermissionError } from '@/lib/workspace-permissions';
import { getCurrentUser } from '@/lib/session';
import {
  assertDocumentPathAvailable,
  DocumentPathConflictError,
  generateUniqueDocumentPath,
} from '@/lib/document-path-utils';
import { generateUniqueGitHubPath } from '@/lib/github-path-utils';

const saveAsSchema = z.object({
  title: z.string().min(1).max(200),
  workspaceId: z.string().optional(), // Can save to different workspace
  path: z.string().optional(),
  phase: z.enum(['PLANNING', 'DEVELOPMENT', 'REVIEW', 'COMPLETE', 'ARCHIVED']).optional(),
  type: z
    .enum([
      'GENERAL',
      'SPECIFICATION',
      'MEETING_NOTES',
      'API_DOCS',
      'GUIDE',
      'RFC',
      'TEMPLATE',
      'FOLDER',
    ])
    .optional(),
  emoji: z.string().optional(),
});

// POST /api/documents/[id]/save-as - Save document as new document
export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id: sourceDocumentId } = await params;
    const body = await request.json();
    const data = saveAsSchema.parse(body);

    // Get source document
    const sourceDocument = await prisma.document.findUnique({
      where: { id: sourceDocumentId },
      select: {
        workspaceId: true,
        content: true,
        title: true,
        emoji: true,
        coverImage: true,
        phase: true,
        type: true,
        wordCount: true,
        readingTime: true,
        properties: true,
      },
    });

    if (!sourceDocument) {
      return NextResponse.json({ error: 'Source document not found' }, { status: 404 });
    }

    // Check read permission on source
    await assertPermission(
      user.id,
      sourceDocument.workspaceId,
      WORKSPACE_PERMISSION.DOCUMENTS_VIEW
    );

    const targetWorkspaceId = data.workspaceId || sourceDocument.workspaceId;
    const targetPhase = data.phase || sourceDocument.phase;
    const targetType = data.type || sourceDocument.type;

    // Check write permission on target workspace
    await assertPermission(user.id, targetWorkspaceId, WORKSPACE_PERMISSION.DOCUMENTS_CREATE);

    // Generate unique path if not provided
    const path =
      data.path ||
      (await generateUniqueDocumentPath({
        workspaceId: targetWorkspaceId,
        phase: targetPhase,
        type: targetType,
        title: data.title,
      }));

    if (data.path) {
      await assertDocumentPathAvailable({
        workspaceId: targetWorkspaceId,
        path: data.path,
      });
    }

    const githubPath = await generateUniqueGitHubPath({
      workspaceId: targetWorkspaceId,
      phase: targetPhase,
      type: targetType,
      title: data.title,
    });

    // Create new document with content from source
    const newDocument = await prisma.document.create({
      data: {
        title: data.title,
        content: sourceDocument.content,
        path,
        workspaceId: targetWorkspaceId,
        authorId: user.id,
        emoji: data.emoji || sourceDocument.emoji,
        coverImage: sourceDocument.coverImage,
        status: 'DRAFT',
        phase: targetPhase,
        type: targetType,
        githubPath,
        githubAutoGenerated: true,
        wordCount: sourceDocument.wordCount,
        readingTime: sourceDocument.readingTime,
        properties: sourceDocument.properties || {},
      },
    });

    // Create initial version
    await prisma.version.create({
      data: {
        documentId: newDocument.id,
        content: newDocument.content,
        message: `Saved as new document from "${sourceDocument.title}"`,
        sha: crypto.createHash('sha256').update(newDocument.content).digest('hex'),
        authorId: user.id,
        version: 1,
      },
    });

    // Create activity log
    await ActivityTracker.create({
      type: 'DOCUMENT_CREATED',
      actorId: user.id,
      workspaceId: targetWorkspaceId,
      entityType: 'document',
      entityId: newDocument.id,
      metadata: {
        title: newDocument.title,
        sourceDocumentTitle: sourceDocument.title,
      },
    });

    return NextResponse.json(newDocument);
  } catch (error) {
    if (error instanceof WorkspacePermissionError) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }

    if (error instanceof DocumentPathConflictError) {
      return NextResponse.json({ error: error.message }, { status: 409 });
    }

    console.error('Error saving document as new:', error);
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.issues }, { status: 400 });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
