'use client';

import { useState, useEffect, useMemo, useRef, type MouseEvent } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { GlassCard } from '@/components/ui/glass-card';
import EditorToolbar from '@/components/EditorToolbar';
import { LockStatusBanner } from '@/components/LockStatusBanner';
import { DocumentLockIndicator } from '@/components/DocumentLockIndicator';
import { UserPresenceAvatars } from '@/components/UserPresenceAvatars';
import { FavoriteToggleButton } from '@/components/FavoriteToggleButton';
import { CommentsDialog } from '@/components/comments-dialog';
import { DocumentGitHubSync } from '@/components/DocumentGitHubSync';
import { ErrorBoundary } from '@/components/ErrorBoundary';
import { CommandPalette } from '@/components/editor/CommandPalette';
import { useDocumentLock } from '@/hooks/useDocumentLock';
import {
  Save,
  X,
  Edit3,
  Lock,
  Edit,
  AlertCircle,
  FileText,
  GitBranch,
  Sparkles,
  Github,
} from 'lucide-react';
import { useEditor, EditorContent } from '@tiptap/react';
import { getTipTapExtensions } from '@/components/TipTapExtensions';
import { Session } from 'next-auth';

interface DocumentEditorProps {
  document: {
    id: string;
    title: string;
    content: string;
    path: string;
    githubPath?: string | null;
    githubAutoGenerated?: boolean;
    favorites?: Array<{ id: string }>;
  };
  canEdit: boolean;
  canUseGitHubSync: boolean;
  workspaceId: string;
  session: Session | null;
}

function normalizeEditorContent(html: string): string {
  if (!html) return '';

  if (typeof window !== 'undefined') {
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');
    return doc.body.innerHTML.replace(/\s+/g, ' ').replace(/> </g, '><').trim();
  }

  return html.replace(/\s+/g, ' ').replace(/> </g, '><').trim();
}

export function DocumentEditor({
  document,
  canEdit,
  canUseGitHubSync,
  workspaceId,
  session,
}: DocumentEditorProps) {
  const router = useRouter();
  const [isEditing, setIsEditing] = useState(false);
  const [content, setContent] = useState(document.content);
  const [commitMessage, setCommitMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [hasChanges, setHasChanges] = useState(false);
  const [showVersionMessageInput, setShowVersionMessageInput] = useState(false);
  const [showCommandPalette, setShowCommandPalette] = useState(false);
  const [showGitHubSyncDialog, setShowGitHubSyncDialog] = useState(false);
  const [wordStats, setWordStats] = useState({ words: 0 });
  const [workspaceMembers, setWorkspaceMembers] = useState<
    Array<{ id: string; name: string | null; email: string }>
  >([]);
  const [mentionQuery, setMentionQuery] = useState<string | null>(null);
  const [mentionRange, setMentionRange] = useState<{ from: number; to: number } | null>(null);
  const [notificationPreviewMentions, setNotificationPreviewMentions] = useState<string[]>([]);
  const [pendingRecoveredDraft, setPendingRecoveredDraft] = useState<{
    content: string;
    updatedAt?: number;
  } | null>(null);
  const normalizedDocumentContent = useMemo(
    () => normalizeEditorContent(document.content),
    [document.content]
  );
  const [savedContent, setSavedContent] = useState(normalizedDocumentContent);
  const [lastAutoSavedAt, setLastAutoSavedAt] = useState<Date | null>(null);
  const [lastAutoSavedContent, setLastAutoSavedContent] = useState(normalizedDocumentContent);
  const autoSaveInFlightRef = useRef(false);
  const hasTriedDraftRestoreRef = useRef(false);
  const draftStorageKey = useMemo(
    () => `dochub:draft:${document.id}:${session?.user?.id ?? 'anonymous'}`,
    [document.id, session?.user?.id]
  );

  const calculateWordStats = (plainText: string) => {
    const cleaned = plainText.replace(/\s+/g, ' ').trim();
    const words = cleaned ? cleaned.split(' ').length : 0;

    return {
      words,
    };
  };

  const resolveMentionHandle = (member: { id: string; name: string | null; email: string }) => {
    if (member.name) {
      return member.name.replace(/\s+/g, '').toLowerCase();
    }
    return member.email.split('@')[0].toLowerCase();
  };

  const refreshMentionPreview = (plainText: string) => {
    const handles = Array.from(plainText.matchAll(/@(\w+)/g)).map((match) =>
      match[1].toLowerCase()
    );
    const matchedMentions = workspaceMembers
      .filter((member) => handles.includes(resolveMentionHandle(member)))
      .map((member) => `@${resolveMentionHandle(member)}`);

    setNotificationPreviewMentions(Array.from(new Set(matchedMentions)));
  };

  const saveDraftLocally = (draftContent: string) => {
    if (typeof window === 'undefined') {
      return;
    }

    try {
      window.localStorage.setItem(
        draftStorageKey,
        JSON.stringify({
          content: draftContent,
          updatedAt: Date.now(),
        })
      );
    } catch {
      // Ignore local draft storage failures
    }
  };

  const clearLocalDraft = () => {
    if (typeof window === 'undefined') {
      return;
    }

    try {
      window.localStorage.removeItem(draftStorageKey);
    } catch {
      // Ignore local draft cleanup failures
    }
  };

  const saveAutoDraftToServer = async (draftContent: string) => {
    if (!hasLock || autoSaveInFlightRef.current) {
      return;
    }

    const normalizedDraft = normalizeEditorContent(draftContent);
    if (normalizedDraft === lastAutoSavedContent) {
      return;
    }

    autoSaveInFlightRef.current = true;
    try {
      const response = await fetch(`/api/documents/${document.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content: draftContent,
          message: 'Auto-save draft',
          createVersion: true,
          isAutoSave: true,
          isDraft: true,
        }),
      });

      if (response.ok) {
        setLastAutoSavedAt(new Date());
        setLastAutoSavedContent(normalizedDraft);
      }
    } catch {
      // Ignore autosave network failures; local draft still protects data
    } finally {
      autoSaveInFlightRef.current = false;
    }
  };

  // Track document access for "Recent Documents"
  useEffect(() => {
    const trackAccess = async () => {
      try {
        await fetch('/api/recent', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ documentId: document.id }),
        });
      } catch (error) {
        // Silently fail - not critical
        console.error('Failed to track document access:', error);
      }
    };

    trackAccess();
  }, [document.id]);

  useEffect(() => {
    const loadWorkspaceMembers = async () => {
      try {
        const response = await fetch(`/api/workspaces/${workspaceId}/members`);
        if (!response.ok) {
          return;
        }
        const data = await response.json();
        const members = Array.isArray(data) ? data : (data.members ?? []);
        setWorkspaceMembers(
          members
            .map(
              (member: { user?: { id: string; name: string | null; email: string } }) => member.user
            )
            .filter(
              (
                user: { id: string; name: string | null; email: string } | undefined
              ): user is {
                id: string;
                name: string | null;
                email: string;
              } => !!user
            )
        );
      } catch {
        // Ignore mention member-loading errors
      }
    };

    loadWorkspaceMembers();
  }, [workspaceId]);

  // TipTap editor initialization with advanced extensions
  const editor = useEditor({
    extensions: getTipTapExtensions(),
    content: document.content,
    editable: isEditing,
    immediatelyRender: false, // Fix SSR hydration mismatch
    onUpdate: ({ editor }) => {
      const newContent = editor.getHTML();
      const normalizedNewContent = normalizeEditorContent(newContent);
      const plainText = editor.getText();
      setContent(newContent);
      setHasChanges(normalizedNewContent !== savedContent);
      setWordStats(calculateWordStats(plainText));

      markLockActivity();

      const { from } = editor.state.selection;
      const textBefore = editor.state.doc.textBetween(Math.max(0, from - 60), from, ' ', ' ');
      const mentionMatch = textBefore.match(/@(\w*)$/);
      if (mentionMatch) {
        setMentionQuery(mentionMatch[1].toLowerCase());
        setMentionRange({ from: from - mentionMatch[0].length, to: from });
      } else {
        setMentionQuery(null);
        setMentionRange(null);
      }

      refreshMentionPreview(plainText);
    },
    editorProps: {
      attributes: {
        class:
          'prose prose-invert max-w-none focus:outline-none min-h-[500px] px-8 py-6 text-white',
      },
      handleKeyDown: (view, event) => {
        if (event.key === '/' && isEditing) {
          const { $from } = view.state.selection;
          const textBeforeCursor = $from.parent.textBetween(0, $from.parentOffset, ' ', ' ');
          if (!textBeforeCursor.trim()) {
            event.preventDefault();
            setShowCommandPalette(true);
            return true;
          }
        }
        return false;
      },
    },
  });

  // Document lock management
  const {
    hasLock,
    lockInfo,
    isLoading: lockLoading,
    error: lockError,
    markLockActivity,
    acquireLock,
    releaseLock,
  } = useDocumentLock({
    documentId: document.id,
    enabled: canEdit, // Only check locks if user can edit
    onLockAcquired: () => {
      toast.success('Lock acquired - you can now edit');
      setIsEditing(true);
    },
    onLockLost: () => {
      toast.error('Lock expired - your changes may not be saved');
      setIsEditing(false);
    },
    onLockUnavailable: (info) => {
      if (info.lock) {
        const name = info.lock.userName || info.lock.userEmail;
        toast.error(`Document is being edited by ${name}`);
      }
    },
  });

  // Cleanup lock on page unload/navigation + autosave protection
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (hasChanges) {
        saveDraftLocally(content);

        if (hasLock) {
          fetch(`/api/documents/${document.id}`, {
            method: 'PATCH',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              content,
              message: 'Auto-save draft on tab close',
              createVersion: true,
              isAutoSave: true,
              isDraft: true,
            }),
            keepalive: true,
          }).catch(() => {
            // Silent failure is acceptable; local draft is fallback
          });
        }
      }

      if (hasLock) {
        // Release lock before page unload (best effort)
        fetch(`/api/documents/${document.id}/lock`, {
          method: 'DELETE',
          headers: { 'Content-Type': 'application/json' },
          keepalive: true, // Allows request to complete even during page unload
        }).catch(() => {
          // Silent failure is acceptable during unload
        });

        // Warn user if they have unsaved changes
        if (hasChanges) {
          e.preventDefault();
          e.returnValue = '';
        }
      }
    };

    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [hasLock, hasChanges, content, document.id, draftStorageKey]);

  // Cleanup any stale locks on mount
  useEffect(() => {
    const cleanupStaleLock = async () => {
      try {
        const response = await fetch(`/api/documents/${document.id}/lock`);
        const data = await response.json();

        // If we have our own lock from a previous session, release it
        if (data.locked && data.isOwnLock) {
          await fetch(`/api/documents/${document.id}/lock`, {
            method: 'DELETE',
          });
        }
      } catch (err) {
        console.error('Failed to cleanup stale lock:', err);
      }
    };

    cleanupStaleLock();
  }, [document.id]);

  // Presence heartbeat — register current user as viewing/editing this document
  useEffect(() => {
    const updatePresence = () => {
      fetch(`/api/workspaces/${workspaceId}/documents/${document.id}/presence`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({}),
        keepalive: true,
      }).catch(() => {
        // Ignore presence failures — non-critical
      });
    };

    updatePresence();
    const interval = window.setInterval(updatePresence, 15000);

    return () => window.clearInterval(interval);
  }, [document.id, workspaceId]);

  useEffect(() => {
    setContent(document.content);
    setSavedContent(normalizedDocumentContent);
    setLastAutoSavedContent(normalizedDocumentContent);
    setHasChanges(false);
    setWordStats(calculateWordStats(editor?.getText() || ''));
    if (editor && document.content !== editor.getHTML()) {
      editor.commands.setContent(document.content);
    }
  }, [document.content, normalizedDocumentContent, editor]);

  useEffect(() => {
    if (!isEditing || typeof window === 'undefined') {
      return;
    }

    const timeout = window.setTimeout(() => {
      if (hasChanges) {
        saveDraftLocally(content);
      }
    }, 500);

    return () => window.clearTimeout(timeout);
  }, [isEditing, hasChanges, content, draftStorageKey]);

  useEffect(() => {
    if (!isEditing || !hasLock || !hasChanges) {
      return;
    }

    const interval = window.setInterval(() => {
      void saveAutoDraftToServer(content);
    }, 15000);

    return () => window.clearInterval(interval);
  }, [isEditing, hasLock, hasChanges, content, lastAutoSavedContent]);

  useEffect(() => {
    if (!isEditing) {
      hasTriedDraftRestoreRef.current = false;
      setPendingRecoveredDraft(null);
      return;
    }

    if (!editor || hasTriedDraftRestoreRef.current || typeof window === 'undefined') {
      return;
    }

    hasTriedDraftRestoreRef.current = true;

    try {
      const rawDraft = window.localStorage.getItem(draftStorageKey);
      if (!rawDraft) {
        return;
      }

      const parsed = JSON.parse(rawDraft) as { content?: string; updatedAt?: number };
      const draftContent = parsed.content;
      if (!draftContent) {
        return;
      }

      const normalizedDraft = normalizeEditorContent(draftContent);
      if (normalizedDraft === normalizedDocumentContent) {
        window.localStorage.removeItem(draftStorageKey);
        return;
      }

      setPendingRecoveredDraft({
        content: draftContent,
        updatedAt: parsed.updatedAt,
      });
    } catch {
      // Ignore malformed local draft
    }
  }, [isEditing, editor, draftStorageKey, normalizedDocumentContent]);

  useEffect(() => {
    if (!isEditing) {
      return;
    }

    if (typeof window === 'undefined') {
      return;
    }

    const previousOverflow = window.document.body.style.overflow;
    const wasEditingClassPresent = window.document.body.classList.contains('document-editing-mode');
    const navElement = window.document.querySelector<HTMLElement>("[data-document-navbar='true']");
    const sidebarElement = window.document.querySelector<HTMLElement>(
      "[data-document-sidebar='true']"
    );
    const previousNavDisplay = navElement?.style.display;
    const previousSidebarDisplay = sidebarElement?.style.display;

    window.document.body.style.overflow = 'hidden';
    window.document.body.classList.add('document-editing-mode');
    if (navElement) {
      navElement.style.display = 'none';
    }
    if (sidebarElement) {
      sidebarElement.style.display = 'none';
    }

    return () => {
      window.document.body.style.overflow = previousOverflow;
      if (navElement) {
        navElement.style.display = previousNavDisplay ?? '';
      }
      if (sidebarElement) {
        sidebarElement.style.display = previousSidebarDisplay ?? '';
      }
      if (!wasEditingClassPresent) {
        window.document.body.classList.remove('document-editing-mode');
      }
    };
  }, [isEditing]);

  // Update editor editable state
  useEffect(() => {
    if (editor) {
      editor.setEditable(isEditing);
    }
  }, [isEditing, editor]);

  const handleContentChange = (newContent: string) => {
    const normalizedNewContent = normalizeEditorContent(newContent);
    setContent(newContent);
    setHasChanges(normalizedNewContent !== savedContent);
  };

  const insertMention = (userId: string) => {
    if (!editor || !mentionRange) {
      return;
    }

    const member = workspaceMembers.find((workspaceMember) => workspaceMember.id === userId);
    if (!member) {
      return;
    }

    const handle = resolveMentionHandle(member);
    editor
      .chain()
      .focus()
      .deleteRange({ from: mentionRange.from, to: mentionRange.to })
      .insertMention({
        id: member.id,
        label: handle,
      })
      .insertContent(' ')
      .run();

    setMentionQuery(null);
    setMentionRange(null);
  };

  const handleRestoreDraft = () => {
    if (!editor || !pendingRecoveredDraft) {
      return;
    }

    setContent(pendingRecoveredDraft.content);
    editor.commands.setContent(pendingRecoveredDraft.content);
    setHasChanges(true);
    setPendingRecoveredDraft(null);
    toast.success('Recovered unsaved draft from previous session');
  };

  const handleDiscardDraft = () => {
    clearLocalDraft();
    setPendingRecoveredDraft(null);
    toast.success('Discarded local draft');
  };

  const handleReplaceExisting = async () => {
    if (!hasLock) {
      toast.error('Cannot save without edit lock');
      return;
    }

    setError('');
    setLoading(true);

    try {
      const response = await fetch(`/api/documents/${document.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content,
          createVersion: false,
          isAutoSave: false,
          isDraft: false,
        }),
      });

      if (response.status === 423) {
        const data = await response.json();
        toast.error(data.error || 'Document is locked by another user');
        setIsEditing(false);
        await releaseLock();
        return;
      }

      if (!response.ok) {
        const data = await response.json();
        setError(data.error || 'Failed to save document');
        toast.error(data.error || 'Failed to save document');
        return;
      }

      await releaseLock();
      toast.success('Document updated (no version created)');
      setIsEditing(false);
      setShowVersionMessageInput(false);
      setCommitMessage('');
      setSavedContent(normalizeEditorContent(content));
      setLastAutoSavedContent(normalizeEditorContent(content));
      setHasChanges(false);
      setPendingRecoveredDraft(null);
      clearLocalDraft();
      router.refresh();
    } catch (err) {
      setError('An error occurred. Please try again.');
      toast.error('An error occurred. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleSaveNewVersion = async () => {
    if (!hasLock) {
      toast.error('Cannot save without edit lock');
      return;
    }

    if (!commitMessage.trim()) {
      setError('Commit message is required for new version');
      toast.error('Please enter a commit message');
      return;
    }

    setError('');
    setLoading(true);

    try {
      const response = await fetch(`/api/documents/${document.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content,
          message: commitMessage,
          createVersion: true,
          isAutoSave: false,
          isDraft: false,
        }),
      });

      const data = await response.json();

      if (response.status === 423) {
        toast.error(data.error || 'Document is locked by another user');
        setIsEditing(false);
        await releaseLock();
        return;
      }

      if (!response.ok) {
        setError(data.error || 'Failed to save document');
        toast.error(data.error || 'Failed to save document');
        return;
      }

      if (!data.versionCreated) {
        setError('No content changes detected, so no new version was created');
        toast.error('No content changes detected, so no new version was created');
        return;
      }

      await releaseLock();
      toast.success('New version saved successfully!');
      setIsEditing(false);
      setShowVersionMessageInput(false);
      setCommitMessage('');
      setSavedContent(normalizeEditorContent(content));
      setLastAutoSavedContent(normalizeEditorContent(content));
      setHasChanges(false);
      setPendingRecoveredDraft(null);
      clearLocalDraft();
      router.refresh();
    } catch (err) {
      setError('An error occurred. Please try again.');
      toast.error('An error occurred. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = async () => {
    // Update UI immediately
    setIsEditing(false);
    setShowVersionMessageInput(false);
    setContent(document.content);
    setCommitMessage('');
    setError('');
    setHasChanges(false);
    setPendingRecoveredDraft(null);
    clearLocalDraft();

    // Release lock in background
    try {
      await releaseLock();
      toast.success('Edit cancelled');
    } catch (err) {
      console.error('Failed to release lock:', err);
      // Don't show error to user since they're cancelling anyway
    }
  };

  useEffect(() => {
    if (isEditing || !hasLock) {
      return;
    }

    void releaseLock();
  }, [isEditing, hasLock, releaseLock]);

  const handleStartEdit = async () => {
    if (!canEdit) {
      toast.error('You do not have permission to edit this document');
      return;
    }

    // Try to acquire lock
    const acquired = await acquireLock();
    if (!acquired) {
      // Lock acquisition failed - error already shown via toast
      return;
    }
    // isEditing will be set to true by onLockAcquired callback
  };

  const handleReadOnlyLinkClick = (event: MouseEvent<HTMLDivElement>) => {
    if (isEditing) {
      return;
    }

    const target = event.target as HTMLElement | null;
    const anchor = target?.closest('a[href]') as HTMLAnchorElement | null;
    if (!anchor) {
      return;
    }

    const href = anchor.getAttribute('href');
    if (!href) {
      return;
    }

    event.preventDefault();
    event.stopPropagation();

    if (href.startsWith('/')) {
      window.location.assign(href);
      return;
    }

    window.open(href, '_blank', 'noopener,noreferrer');
  };

  return (
    <GlassCard
      className={`overflow-hidden border-white/10 bg-slate-950/35 shadow-2xl shadow-purple-500/5 ${
        isEditing ? 'fixed inset-0 z-120 overflow-y-auto rounded-none border-0 bg-slate-950' : ''
      }`}
      hover={false}
    >
      <div className={`${isEditing ? 'min-h-screen p-4 md:p-6' : 'p-5 md:p-6'}`}>
        {/* Lock Status Banner - Show if document locked by someone else */}
        {lockInfo?.locked && lockInfo.lock && !hasLock && (
          <LockStatusBanner lockInfo={lockInfo.lock} className="mb-6" />
        )}

        {isEditing && pendingRecoveredDraft && (
          <div className="mb-4 rounded-2xl border border-amber-500/30 bg-amber-500/10 p-4">
            <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
              <div className="text-sm text-amber-100">
                Unsaved draft found from a previous session
                {pendingRecoveredDraft.updatedAt && (
                  <span className="ml-2 text-xs text-amber-300">
                    ({new Date(pendingRecoveredDraft.updatedAt).toLocaleString()})
                  </span>
                )}
              </div>
              <div className="flex items-center gap-2">
                <Button
                  onClick={handleDiscardDraft}
                  variant="outline"
                  size="sm"
                  className="border-white/10 bg-transparent text-slate-200 hover:bg-white/10"
                >
                  Discard
                </Button>
                <Button
                  onClick={handleRestoreDraft}
                  size="sm"
                  className="bg-linear-to-r from-amber-500 to-orange-500 text-white"
                >
                  Restore Draft
                </Button>
              </div>
            </div>
          </div>
        )}

        {/* Lock Error Alert */}
        {lockError && !lockInfo?.locked && (
          <div className="mb-4 flex items-start gap-2 rounded-lg border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">
            <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
            <span>{lockError}</span>
          </div>
        )}

        {/* Enhanced Modern Header */}
        <div className="mb-6 rounded-2xl border border-white/10 bg-linear-to-r from-slate-900/80 via-slate-900/65 to-slate-800/70 p-5 shadow-xl shadow-purple-500/5">
          <div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between">
            <div className="min-w-0 flex-1">
              <div className="flex flex-wrap items-start gap-3">
                <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-linear-to-br from-purple-600 to-fuchsia-600 shadow-lg shadow-purple-500/20">
                  <FileText className="h-5 w-5 text-white" />
                </div>
                <div className="min-w-0 flex-1">
                  <h2 className="truncate text-2xl font-bold text-white">{document.title}</h2>
                  <div className="mt-1 flex flex-wrap items-center gap-2 text-xs">
                    <p className="truncate text-slate-400">
                      {document.githubPath ?? document.path}
                    </p>
                  </div>
                </div>
              </div>

              <div className="mt-4 flex flex-wrap items-center gap-2">
                {canEdit && <DocumentLockIndicator documentId={document.id} />}

                {!canEdit && (
                  <div className="flex items-center gap-1.5 rounded-lg border border-white/10 bg-slate-800/50 px-2.5 py-1 text-xs font-medium text-slate-400">
                    <Lock className="h-3.5 w-3.5" />
                    Read-only
                  </div>
                )}

                {isEditing && hasChanges && (
                  <div className="flex animate-pulse items-center gap-1.5 rounded-lg border border-amber-500/30 bg-amber-500/10 px-2.5 py-1 text-xs font-medium text-amber-400">
                    <Edit3 className="h-3.5 w-3.5" />
                    Unsaved changes
                  </div>
                )}
              </div>
            </div>

            <div className="flex flex-wrap items-center gap-2 xl:justify-end">
              {/* User Presence Avatars */}
              {session?.user?.id && (
                <UserPresenceAvatars
                  documentId={document.id}
                  workspaceId={workspaceId}
                  currentUserId={session.user.id}
                  maxVisible={4}
                  showCursors={isEditing}
                />
              )}

              <div className="h-6 w-px bg-white/10" />

              {/* Favorite Toggle */}
              <FavoriteToggleButton
                documentId={document.id}
                initialIsFavorite={Boolean(document.favorites?.length)}
                size="sm"
                variant="ghost"
              />

              {isEditing && (
                <>
                  <div className="h-6 w-px bg-white/10" />
                  <CommentsDialog documentId={document.id} workspaceId={workspaceId} />
                </>
              )}

              <div className="h-6 w-px bg-white/10" />

              {isEditing ? (
                <>
                  {canUseGitHubSync && (
                    <Button
                      onClick={() => setShowGitHubSyncDialog(true)}
                      variant="outline"
                      size="sm"
                      className="gap-1.5 border-white/20 bg-slate-900/60 text-slate-100 hover:border-purple-400/50 hover:bg-slate-800/90 hover:text-white"
                    >
                      <Github className="h-4 w-4" />
                      GitHub Sync
                    </Button>
                  )}
                  <Button
                    onClick={handleCancel}
                    variant="outline"
                    size="sm"
                    disabled={loading}
                    className="gap-1.5 border-white/20 bg-slate-900/60 text-slate-100 hover:border-purple-400/50 hover:bg-slate-800/90 hover:text-white"
                  >
                    <X className="h-4 w-4" />
                    Cancel
                  </Button>
                  <Button
                    onClick={handleReplaceExisting}
                    variant="outline"
                    size="sm"
                    disabled={loading || !hasChanges}
                    className="gap-1.5 border-white/20 bg-slate-900/70 text-white hover:border-purple-400/50 hover:bg-slate-800/95 hover:text-white"
                  >
                    <Save className="h-4 w-4" />
                    {loading ? 'Saving...' : 'Save'}
                  </Button>
                  <Button
                    onClick={() => {
                      if (!showVersionMessageInput) {
                        setShowVersionMessageInput(true);
                        setError('');
                        return;
                      }
                      handleSaveNewVersion();
                    }}
                    size="sm"
                    disabled={loading || !hasChanges}
                    className="gap-1.5 bg-linear-to-r from-purple-600 to-fuchsia-600 text-white hover:shadow-lg hover:shadow-purple-600/20"
                  >
                    <Save className="h-4 w-4" />
                    {loading ? 'Saving...' : 'Save Version'}
                  </Button>
                </>
              ) : canEdit && !lockInfo?.locked ? (
                <Button
                  onClick={handleStartEdit}
                  size="sm"
                  disabled={lockLoading}
                  className="gap-1.5 bg-linear-to-r from-purple-600 to-fuchsia-600 text-white hover:shadow-lg hover:shadow-purple-600/20"
                >
                  <Edit className="h-4 w-4" />
                  {lockLoading ? 'Acquiring...' : 'Edit'}
                </Button>
              ) : null}
            </div>
          </div>
        </div>

        {/* Commit Message Input (only when editing) */}
        {isEditing && showVersionMessageInput && (
          <div className="mb-6 rounded-2xl border border-purple-500/30 bg-linear-to-br from-purple-500/10 to-fuchsia-500/10 p-5 shadow-lg shadow-purple-500/5">
            <label className="mb-2 flex items-center gap-2 text-sm font-semibold text-white">
              <GitBranch className="h-4 w-4 text-purple-400" />
              Version Message
              <span className="text-xs font-normal text-slate-400">(required for new version)</span>
            </label>
            <Input
              placeholder="Describe your changes (e.g., 'Updated introduction section')"
              value={commitMessage}
              onChange={(e) => setCommitMessage(e.target.value)}
              className="mb-3 border-white/10 bg-slate-900/50 text-white shadow-sm placeholder:text-slate-500 focus:border-purple-500/50"
              disabled={loading}
            />
            {error && <p className="mb-2 text-sm font-medium text-red-400">{error}</p>}
            <div className="flex items-start gap-2 rounded-lg border border-blue-500/20 bg-blue-500/10 p-3 text-xs text-blue-300">
              <Sparkles className="mt-0.5 h-3.5 w-3.5 shrink-0 text-blue-400" />
              <div>
                <span className="font-semibold">Save:</span> Quick update without version history •{' '}
                <span className="font-semibold">Save Version:</span> Creates tracked version with
                message
              </div>
            </div>
          </div>
        )}

        {/* Edit Prompt */}
        {!isEditing && canEdit && (
          <div className="mb-6 rounded-2xl border border-purple-500/30 bg-linear-to-r from-purple-500/10 to-blue-500/10 p-4 shadow-lg shadow-purple-500/5">
            <div className="flex items-center gap-2.5 text-sm font-medium text-white">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-purple-600 shadow-md">
                <Edit3 className="h-4 w-4 text-white" />
              </div>
              <span>
                Click <strong className="font-semibold text-purple-400">Edit</strong> above to start
                editing this document
              </span>
            </div>
          </div>
        )}

        {/* Word Count */}
        {isEditing && (
          <div className="mb-6 rounded-2xl border border-white/10 bg-slate-900/40 p-4">
            <div className="flex flex-wrap items-center gap-3 text-sm text-slate-300">
              <span>
                <strong className="text-white">Words:</strong> {wordStats.words}
              </span>
              {lastAutoSavedAt && (
                <span className="text-xs text-emerald-300">
                  Auto-saved {lastAutoSavedAt.toLocaleTimeString()}
                </span>
              )}
            </div>
          </div>
        )}

        {/* Mention autocomplete and notification preview */}
        {isEditing && mentionQuery !== null && (
          <div className="mb-4 rounded-xl border border-purple-500/30 bg-slate-900/90 p-2">
            <p className="mb-2 text-xs text-slate-400">Mention someone</p>
            <div className="max-h-40 space-y-1 overflow-y-auto">
              {workspaceMembers
                .filter((member) => {
                  const handle = resolveMentionHandle(member);
                  const name = (member.name ?? '').toLowerCase();
                  return handle.startsWith(mentionQuery) || name.startsWith(mentionQuery);
                })
                .slice(0, 6)
                .map((member) => {
                  const handle = resolveMentionHandle(member);
                  return (
                    <button
                      key={member.id}
                      type="button"
                      onClick={() => insertMention(member.id)}
                      className="flex w-full items-center justify-between rounded-lg px-3 py-2 text-left text-sm text-slate-200 hover:bg-white/10"
                    >
                      <span className="truncate">{member.name || member.email}</span>
                      <span className="text-xs text-purple-300">@{handle}</span>
                    </button>
                  );
                })}
            </div>
          </div>
        )}

        {isEditing && notificationPreviewMentions.length > 0 && (
          <div className="mb-4 rounded-xl border border-blue-500/20 bg-blue-500/10 p-3 text-xs text-blue-200">
            Notification preview: {notificationPreviewMentions.join(', ')} will be notified when
            mentions are processed.
          </div>
        )}

        {/* TipTap Rich Text Editor with Modern Toolbar */}
        <div className="relative">
          {isEditing && editor && (
            <div className="sticky top-0 z-50 mb-4 rounded-2xl border border-purple-500/30 bg-linear-to-br from-slate-900 via-slate-800 to-slate-900 p-4 shadow-lg shadow-purple-500/10">
              <div className="flex flex-wrap items-center gap-2">
                <EditorToolbar editor={editor} workspaceId={workspaceId} />
              </div>
            </div>
          )}
          <div
            onClickCapture={handleReadOnlyLinkClick}
            className={`rounded-2xl border border-white/10 bg-linear-to-br from-slate-900/80 via-slate-900/70 to-slate-800/80 shadow-2xl ${!isEditing ? 'opacity-70' : ''}`}
          >
            <div className="prose prose-invert max-w-none">
              <ErrorBoundary
                fallback={
                  <div className="rounded-md border-2 border-red-500/30 bg-red-500/10 p-4">
                    <p className="font-semibold text-red-400">Editor Error</p>
                    <p className="text-sm text-red-300">
                      The editor encountered an error. Please refresh the page.
                    </p>
                  </div>
                }
                onError={(error) => {
                  console.error('Editor error:', error);
                  toast.error('Editor crashed. Please refresh the page.');
                }}
              >
                <EditorContent editor={editor} />
              </ErrorBoundary>
            </div>
          </div>
        </div>
      </div>

      <CommandPalette
        editor={editor}
        isOpen={showCommandPalette}
        onClose={() => setShowCommandPalette(false)}
      />

      {canUseGitHubSync && (
        <DocumentGitHubSync
          documentId={document.id}
          workspaceId={workspaceId}
          documentTitle={document.title}
          open={showGitHubSyncDialog}
          onOpenChange={setShowGitHubSyncDialog}
        />
      )}
    </GlassCard>
  );
}
