'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { GlassCard } from '@/components/ui/glass-card';
import EditorToolbar from '@/components/EditorToolbar';
import { LockStatusBanner } from '@/components/LockStatusBanner';
import { DocumentLockIndicator } from '@/components/DocumentLockIndicator';
import { UserPresenceAvatars } from '@/components/UserPresenceAvatars';
import { FavoriteToggleButton } from '@/components/FavoriteToggleButton';
import { ErrorBoundary } from '@/components/ErrorBoundary';
import { useDocumentLock } from '@/hooks/useDocumentLock';
import {
  Save,
  X,
  Edit3,
  Lock,
  Edit,
  AlertCircle,
  FileText,
  GitBranch,
  Sparkles,
  Github,
} from 'lucide-react';
import { useEditor, EditorContent } from '@tiptap/react';
import { getTipTapExtensions } from '@/components/TipTapExtensions';
import { Session } from 'next-auth';

interface DocumentEditorProps {
  document: {
    id: string;
    title: string;
    content: string;
    path: string;
    githubPath?: string | null;
    githubAutoGenerated?: boolean;
  };
  canEdit: boolean;
  workspaceId: string;
  session: Session | null;
}

export function DocumentEditor({ document, canEdit, workspaceId, session }: DocumentEditorProps) {
  const router = useRouter();
  const [isEditing, setIsEditing] = useState(false);
  const [content, setContent] = useState(document.content);
  const [commitMessage, setCommitMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [hasChanges, setHasChanges] = useState(false);

  // Track document access for "Recent Documents"
  useEffect(() => {
    const trackAccess = async () => {
      try {
        await fetch('/api/recent', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ documentId: document.id }),
        });
      } catch (error) {
        // Silently fail - not critical
        console.error('Failed to track document access:', error);
      }
    };

    trackAccess();
  }, [document.id]);

  // TipTap editor initialization with advanced extensions
  const editor = useEditor({
    extensions: getTipTapExtensions(),
    content: document.content,
    editable: isEditing,
    immediatelyRender: false, // Fix SSR hydration mismatch
    onUpdate: ({ editor }) => {
      const newContent = editor.getHTML();
      setContent(newContent);
      setHasChanges(newContent !== document.content);
    },
    editorProps: {
      attributes: {
        class:
          'prose prose-invert max-w-none focus:outline-none min-h-[500px] px-8 py-6 text-white',
      },
    },
  });

  // Document lock management
  const {
    hasLock,
    lockInfo,
    isLoading: lockLoading,
    error: lockError,
    acquireLock,
    releaseLock,
  } = useDocumentLock({
    documentId: document.id,
    enabled: canEdit, // Only check locks if user can edit
    onLockAcquired: () => {
      toast.success('Lock acquired - you can now edit');
      setIsEditing(true);
    },
    onLockLost: () => {
      toast.error('Lock expired - your changes may not be saved');
      setIsEditing(false);
    },
    onLockUnavailable: (info) => {
      if (info.lock) {
        const name = info.lock.userName || info.lock.userEmail;
        toast.error(`Document is being edited by ${name}`);
      }
    },
  });

  // Cleanup lock on page unload/navigation
  useEffect(() => {
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (hasLock) {
        // Release lock before page unload (best effort)
        fetch(`/api/documents/${document.id}/lock`, {
          method: 'DELETE',
          headers: { 'Content-Type': 'application/json' },
          keepalive: true, // Allows request to complete even during page unload
        }).catch(() => {
          // Silent failure is acceptable during unload
        });

        // Warn user if they have unsaved changes
        if (hasChanges) {
          e.preventDefault();
          e.returnValue = '';
        }
      }
    };

    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [hasLock, hasChanges, document.id]);

  // Cleanup any stale locks on mount
  useEffect(() => {
    const cleanupStaleLock = async () => {
      try {
        const response = await fetch(`/api/documents/${document.id}/lock`);
        const data = await response.json();

        // If we have our own lock from a previous session, release it
        if (data.locked && data.isOwnLock) {
          await fetch(`/api/documents/${document.id}/lock`, {
            method: 'DELETE',
          });
        }
      } catch (err) {
        console.error('Failed to cleanup stale lock:', err);
      }
    };

    cleanupStaleLock();
  }, [document.id]);

  useEffect(() => {
    setContent(document.content);
    setHasChanges(false);
    if (editor && document.content !== editor.getHTML()) {
      editor.commands.setContent(document.content);
    }
  }, [document.content, editor]);

  // Update editor editable state
  useEffect(() => {
    if (editor) {
      editor.setEditable(isEditing);
    }
  }, [isEditing, editor]);

  const handleContentChange = (newContent: string) => {
    setContent(newContent);
    setHasChanges(newContent !== document.content);
  };

  const handleReplaceExisting = async () => {
    if (!hasLock) {
      toast.error('Cannot save without edit lock');
      return;
    }

    setError('');
    setLoading(true);

    try {
      const response = await fetch(`/api/documents/${document.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content,
          createVersion: false,
          isAutoSave: false,
          isDraft: false,
        }),
      });

      if (response.status === 423) {
        const data = await response.json();
        toast.error(data.error || 'Document is locked by another user');
        setIsEditing(false);
        await releaseLock();
        return;
      }

      if (!response.ok) {
        const data = await response.json();
        setError(data.error || 'Failed to save document');
        toast.error(data.error || 'Failed to save document');
        return;
      }

      await releaseLock();
      toast.success('Document updated (no version created)');
      setIsEditing(false);
      setCommitMessage('');
      setHasChanges(false);
      router.refresh();
    } catch (err) {
      setError('An error occurred. Please try again.');
      toast.error('An error occurred. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleSaveNewVersion = async () => {
    if (!hasLock) {
      toast.error('Cannot save without edit lock');
      return;
    }

    if (!commitMessage.trim()) {
      setError('Commit message is required for new version');
      toast.error('Please enter a commit message');
      return;
    }

    setError('');
    setLoading(true);

    try {
      const response = await fetch(`/api/documents/${document.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content,
          message: commitMessage,
          createVersion: true,
          isAutoSave: false,
          isDraft: false,
        }),
      });

      if (response.status === 423) {
        const data = await response.json();
        toast.error(data.error || 'Document is locked by another user');
        setIsEditing(false);
        await releaseLock();
        return;
      }

      if (!response.ok) {
        const data = await response.json();
        setError(data.error || 'Failed to save document');
        toast.error(data.error || 'Failed to save document');
        return;
      }

      await releaseLock();
      toast.success('New version saved successfully!');
      setIsEditing(false);
      setCommitMessage('');
      setHasChanges(false);
      router.refresh();
    } catch (err) {
      setError('An error occurred. Please try again.');
      toast.error('An error occurred. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = async () => {
    // Update UI immediately
    setIsEditing(false);
    setContent(document.content);
    setCommitMessage('');
    setError('');
    setHasChanges(false);

    // Release lock in background
    try {
      await releaseLock();
      toast.success('Edit cancelled');
    } catch (err) {
      console.error('Failed to release lock:', err);
      // Don't show error to user since they're cancelling anyway
    }
  };

  const handleStartEdit = async () => {
    if (!canEdit) {
      toast.error('You do not have permission to edit this document');
      return;
    }

    // Try to acquire lock
    const acquired = await acquireLock();
    if (!acquired) {
      // Lock acquisition failed - error already shown via toast
      return;
    }
    // isEditing will be set to true by onLockAcquired callback
  };

  return (
    <GlassCard className="overflow-hidden" hover={false}>
      <div className="p-6">
        {/* Lock Status Banner - Show if document locked by someone else */}
        {lockInfo?.locked && lockInfo.lock && !hasLock && (
          <LockStatusBanner lockInfo={lockInfo.lock} className="mb-6" />
        )}

        {/* Lock Error Alert */}
        {lockError && !lockInfo?.locked && (
          <div className="mb-4 flex items-start gap-2 rounded-lg border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-300">
            <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
            <span>{lockError}</span>
          </div>
        )}

        {/* Enhanced Modern Header */}
        <div className="mb-6 rounded-xl border border-white/10 bg-slate-900/70 p-6 shadow-sm">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-purple-600 to-fuchsia-600 shadow-lg shadow-purple-500/20">
                <FileText className="h-5 w-5 text-white" />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-white">{document.title}</h2>
                <div className="flex items-center gap-2 text-xs">
                  <p className="text-slate-400">{document.path}</p>
                  {document.githubPath && (
                    <>
                      <span className="text-slate-600">•</span>
                      <div className="flex items-center gap-1 text-slate-500">
                        <Github className="h-3 w-3" />
                        <code className="rounded bg-slate-800/50 px-1.5 py-0.5 font-mono">
                          {document.githubPath}
                        </code>
                        {document.githubAutoGenerated && (
                          <span className="text-[10px] text-slate-600">(auto)</span>
                        )}
                      </div>
                    </>
                  )}
                </div>
              </div>

              {/* Status Badges */}
              {canEdit && <DocumentLockIndicator documentId={document.id} />}

              {!canEdit && (
                <div className="flex items-center gap-1.5 rounded-lg border border-white/10 bg-slate-800/50 px-2.5 py-1 text-xs font-medium text-slate-400">
                  <Lock className="h-3.5 w-3.5" />
                  Read-only
                </div>
              )}

              {hasChanges && (
                <div className="flex animate-pulse items-center gap-1.5 rounded-lg border border-amber-500/30 bg-amber-500/10 px-2.5 py-1 text-xs font-medium text-amber-400">
                  <Edit3 className="h-3.5 w-3.5" />
                  Unsaved
                </div>
              )}
            </div>

            <div className="flex items-center gap-2">
              {/* User Presence Avatars */}
              {session?.user?.id && (
                <UserPresenceAvatars
                  documentId={document.id}
                  workspaceId={workspaceId}
                  currentUserId={session.user.id}
                  maxVisible={4}
                />
              )}

              <div className="h-6 w-px bg-white/10" />

              {/* Favorite Toggle */}
              <FavoriteToggleButton documentId={document.id} size="sm" variant="ghost" />

              <div className="h-6 w-px bg-white/10" />

              {isEditing ? (
                <>
                  <Button
                    onClick={handleCancel}
                    variant="outline"
                    size="sm"
                    disabled={loading}
                    className="gap-1.5 border-white/10 bg-transparent text-slate-300 hover:bg-white/5"
                  >
                    <X className="h-4 w-4" />
                    Cancel
                  </Button>
                  <Button
                    onClick={handleReplaceExisting}
                    variant="outline"
                    size="sm"
                    disabled={loading || !hasChanges}
                    className="gap-1.5 border-white/10 bg-slate-800/50 text-white hover:bg-slate-800"
                  >
                    <Save className="h-4 w-4" />
                    {loading ? 'Saving...' : 'Replace'}
                  </Button>
                  <Button
                    onClick={handleSaveNewVersion}
                    size="sm"
                    disabled={loading || !hasChanges}
                    className="gap-1.5 bg-gradient-to-r from-purple-600 to-fuchsia-600 text-white hover:shadow-lg hover:shadow-purple-600/20"
                  >
                    <Save className="h-4 w-4" />
                    {loading ? 'Saving...' : 'Save Version'}
                  </Button>
                </>
              ) : canEdit && !lockInfo?.locked ? (
                <Button
                  onClick={handleStartEdit}
                  size="sm"
                  disabled={lockLoading}
                  className="gap-1.5 bg-gradient-to-r from-purple-600 to-fuchsia-600 text-white hover:shadow-lg hover:shadow-purple-600/20"
                >
                  <Edit className="h-4 w-4" />
                  {lockLoading ? 'Acquiring...' : 'Edit'}
                </Button>
              ) : null}
            </div>
          </div>
        </div>

        {/* Commit Message Input (only when editing) */}
        {isEditing && (
          <div className="mb-6 rounded-xl border border-purple-500/30 bg-gradient-to-br from-purple-500/10 to-fuchsia-500/10 p-5 shadow-sm">
            <label className="mb-2 flex items-center gap-2 text-sm font-semibold text-white">
              <GitBranch className="h-4 w-4 text-purple-400" />
              Version Message
              <span className="text-xs font-normal text-slate-400">(required for new version)</span>
            </label>
            <Input
              placeholder="Describe your changes (e.g., 'Updated introduction section')"
              value={commitMessage}
              onChange={(e) => setCommitMessage(e.target.value)}
              className="mb-3 border-white/10 bg-slate-900/50 text-white shadow-sm placeholder:text-slate-500 focus:border-purple-500/50"
              disabled={loading}
            />
            {error && <p className="mb-2 text-sm font-medium text-red-400">{error}</p>}
            <div className="flex items-start gap-2 rounded-lg border border-blue-500/20 bg-blue-500/10 p-3 text-xs text-blue-300">
              <Sparkles className="mt-0.5 h-3.5 w-3.5 shrink-0 text-blue-400" />
              <div>
                <span className="font-semibold">Replace:</span> Quick update without version history
                • <span className="font-semibold">Save Version:</span> Creates tracked version with
                message
              </div>
            </div>
          </div>
        )}

        {/* Edit Prompt */}
        {!isEditing && canEdit && (
          <div className="mb-6 rounded-xl border border-purple-500/30 bg-gradient-to-r from-purple-500/10 to-blue-500/10 p-4 shadow-sm">
            <div className="flex items-center gap-2.5 text-sm font-medium text-white">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-purple-600 shadow-md">
                <Edit3 className="h-4 w-4 text-white" />
              </div>
              <span>
                Click <strong className="font-semibold text-purple-400">Edit</strong> above to start
                editing this document
              </span>
            </div>
          </div>
        )}

        {/* TipTap Rich Text Editor with Modern Toolbar */}
        <div className="relative">
          {isEditing && editor && (
            <div className="sticky top-0 z-50 mb-4 rounded-xl border border-purple-500/30 bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-4 shadow-lg shadow-purple-500/10">
              <div className="flex flex-wrap items-center gap-2">
                <EditorToolbar editor={editor} />
              </div>
            </div>
          )}
          <div
            className={`rounded-xl border border-white/10 bg-gradient-to-br from-slate-900/80 via-slate-900/70 to-slate-800/80 shadow-2xl ${!isEditing ? 'pointer-events-none opacity-70' : ''}`}
          >
            <div className="prose prose-invert max-w-none">
              <ErrorBoundary
                fallback={
                  <div className="rounded-md border-2 border-red-500/30 bg-red-500/10 p-4">
                    <p className="font-semibold text-red-400">Editor Error</p>
                    <p className="text-sm text-red-300">
                      The editor encountered an error. Please refresh the page.
                    </p>
                  </div>
                }
                onError={(error) => {
                  console.error('Editor error:', error);
                  toast.error('Editor crashed. Please refresh the page.');
                }}
              >
                <EditorContent editor={editor} />
              </ErrorBoundary>
            </div>
          </div>
        </div>
      </div>
    </GlassCard>
  );
}
