import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { ActivityTracker } from '@/lib/activity';
import { z } from 'zod';
import { WORKSPACE_PERMISSION } from '@/lib/workspace-permission-definitions';
import { assertPermission, WorkspacePermissionError } from '@/lib/workspace-permissions';
import { getCurrentUser } from '@/lib/session';
import {
  assertDocumentPathAvailable,
  DocumentPathConflictError,
  generateUniqueDocumentPath,
  sanitizeCustomPath,
  validateCustomPath,
} from '@/lib/document-path-utils';
import {
  generateUniqueGitHubPath,
  generateUniqueGitHubPathFromCustom,
} from '@/lib/github-path-utils';

const updateDocumentSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  path: z.string().optional(),
  phase: z.enum(['PLANNING', 'DEVELOPMENT', 'REVIEW', 'COMPLETE', 'ARCHIVED']).optional(),
  type: z
    .enum([
      'GENERAL',
      'SPECIFICATION',
      'MEETING_NOTES',
      'API_DOCS',
      'GUIDE',
      'RFC',
      'TEMPLATE',
      'FOLDER',
    ])
    .optional(),
  emoji: z.string().optional(),
  coverImage: z.string().optional(),
  status: z.enum(['DRAFT', 'IN_REVIEW', 'PUBLISHED', 'ARCHIVED']).optional(),
});

// PATCH /api/documents/[id]/settings - Update document settings (rename, etc.)
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id: documentId } = await params;
    const body = await request.json();
    const data = updateDocumentSchema.parse(body);

    // Get document and check permissions
    const document = await prisma.document.findUnique({
      where: { id: documentId },
      select: {
        workspaceId: true,
        title: true,
        phase: true,
        type: true,
      },
    });

    if (!document) {
      return NextResponse.json({ error: 'Document not found' }, { status: 404 });
    }

    // Check permissions
    await assertPermission(user.id, document.workspaceId, WORKSPACE_PERMISSION.DOCUMENTS_EDIT);

    const updateData: typeof data & { githubPath?: string; githubAutoGenerated?: boolean } = {
      ...data,
    };

    // Sanitize and validate custom path if provided
    if (data.path !== undefined) {
      data.path = sanitizeCustomPath(data.path);
      const pathError = validateCustomPath(data.path);
      if (pathError) {
        return NextResponse.json({ error: pathError }, { status: 400 });
      }
    }

    // Keep path/githubPath synced with phase/type/title when one of these changes
    if (data.phase || data.type || data.title) {
      const nextPhase = data.phase || document.phase;
      const nextType = data.type || document.type;
      const nextTitle = data.title || document.title;

      if (data.path === undefined) {
        updateData.path = await generateUniqueDocumentPath({
          workspaceId: document.workspaceId,
          phase: nextPhase,
          type: nextType,
          title: nextTitle,
          excludeDocumentId: documentId,
        });
        // Auto-generate githubPath from phase/type/title
        updateData.githubPath = await generateUniqueGitHubPath({
          workspaceId: document.workspaceId,
          phase: nextPhase,
          type: nextType,
          title: nextTitle,
        });
        updateData.githubAutoGenerated = true;
      }
    }

    // If a custom path was explicitly provided, derive githubPath from it
    if (data.path !== undefined) {
      await assertDocumentPathAvailable({
        workspaceId: document.workspaceId,
        path: data.path,
        excludeDocumentId: documentId,
      });
      updateData.githubPath = await generateUniqueGitHubPathFromCustom(
        data.path,
        document.workspaceId,
        documentId
      );
      updateData.githubAutoGenerated = false;
    }

    // Update document
    const updatedDocument = await prisma.document.update({
      where: { id: documentId },
      data: updateData,
    });

    // Create activity log
    await ActivityTracker.create({
      type: 'DOCUMENT_UPDATED',
      actorId: user.id,
      workspaceId: document.workspaceId,
      entityType: 'document',
      entityId: documentId,
      metadata: {
        title: updatedDocument.title,
      },
    });

    return NextResponse.json(updatedDocument);
  } catch (error) {
    if (error instanceof WorkspacePermissionError) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }

    if (error instanceof DocumentPathConflictError) {
      return NextResponse.json({ error: error.message }, { status: 409 });
    }

    console.error('Error updating document settings:', error);
    if (error instanceof z.ZodError) {
      return NextResponse.json({ error: error.issues }, { status: 400 });
    }
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

// DELETE /api/documents/[id]/settings - Delete document
export async function DELETE(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const user = await getCurrentUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id: documentId } = await params;

    // Get document and check permissions
    const document = await prisma.document.findUnique({
      where: { id: documentId },
      select: {
        workspaceId: true,
      },
    });

    if (!document) {
      return NextResponse.json({ error: 'Document not found' }, { status: 404 });
    }

    await assertPermission(user.id, document.workspaceId, WORKSPACE_PERMISSION.DOCUMENTS_DELETE);

    await ActivityTracker.create({
      type: 'DOCUMENT_DELETED',
      actorId: user.id,
      workspaceId: document.workspaceId,
      entityType: 'document',
      entityId: documentId,
      metadata: {
        title: 'Deleted document',
      },
    });

    // Delete document (cascade will delete all related data)
    await prisma.document.delete({
      where: { id: documentId },
    });

    return NextResponse.json({ success: true });
  } catch (error) {
    if (error instanceof WorkspacePermissionError) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }

    console.error('Error deleting document:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
