/**
 * Automated GitHub Path Mapping
 * Zero-friction path generation for documents
 */

import { prisma } from '@/lib/prisma';
import slugify from 'slugify';

export interface PathMappingConfig {
  defaultRoot?: string;
  useSubfolders?: boolean;
  preserveHierarchy?: boolean;
  fileExtension?: string;
}

/**
 * Get or generate GitHub path for a document
 * If path exists, return it. Otherwise, auto-generate based on title.
 */
export async function getDocumentGitHubPath(
  documentId: string,
  config: PathMappingConfig = {}
): Promise<string> {
  const document = await prisma.document.findUnique({
    where: { id: documentId },
    select: {
      id: true,
      title: true,
      type: true,
      githubPath: true,
      githubAutoGenerated: true,
      parent: {
        select: {
          title: true,
        },
      },
      workspace: {
        include: {
          githubRepos: {
            take: 1,
            orderBy: { createdAt: 'desc' },
          },
        },
      },
    },
  });

  if (!document) {
    throw new Error('Document not found');
  }

  // Return existing GitHub path if available
  if (document.githubPath) {
    return document.githubPath;
  }

  // Auto-generate path
  const generatedPath = await generatePath(document, config);

  // Store the generated path
  await prisma.document.update({
    where: { id: documentId },
    data: {
      githubPath: generatedPath,
      githubAutoGenerated: true,
    },
  });

  return generatedPath;
}

/**
 * Generate a clean GitHub path from document title
 */
export async function generatePath(
  document: {
    title: string;
    type: string;
    parent?: { title: string } | null;
    workspace: {
      githubRepos: Array<{ repoName: string }>;
    };
  },
  config: PathMappingConfig = {}
): Promise<string> {
  const {
    defaultRoot = 'docs',
    useSubfolders = true,
    preserveHierarchy = true,
    fileExtension = '.md',
  } = config;

  const parts: string[] = [defaultRoot];

  // Add type-based subfolder if enabled
  if (useSubfolders) {
    const typeFolder = getTypeFolderName(document.type);
    if (typeFolder) {
      parts.push(typeFolder);
    }
  }

  // Add parent hierarchy if enabled
  if (preserveHierarchy && document.parent) {
    const parentSlug = slugify(document.parent.title, {
      lower: true,
      strict: true,
      remove: /[*+~.()'"!:@]/g,
    });
    parts.push(parentSlug);
  }

  // Add document filename
  const filename = slugify(document.title, {
    lower: true,
    strict: true,
    remove: /[*+~.()'"!:@]/g,
  });

  const fullPath = [...parts, filename + fileExtension].join('/');

  return fullPath;
}

/**
 * Get folder name based on document type
 */
function getTypeFolderName(type: string): string {
  const typeMap: Record<string, string> = {
    SPEC: 'specifications',
    MEETING: 'meeting-notes',
    DECISION: 'decisions',
    TUTORIAL: 'tutorials',
    REFERENCE: 'reference',
    GUIDE: 'guides',
    GENERAL: '',
  };

  return typeMap[type] || '';
}

/**
 * Validate GitHub path format
 */
export function validatePath(path: string): boolean {
  // Check for invalid characters
  const invalidChars = /[<>:"|?*\x00-\x1F]/;
  if (invalidChars.test(path)) {
    return false;
  }

  // Check for valid file extension
  if (!path.endsWith('.md') && !path.endsWith('.mdx')) {
    return false;
  }

  // Check for empty segments
  const segments = path.split('/');
  if (segments.some((seg) => !seg || seg === '.' || seg === '..')) {
    return false;
  }

  return true;
}

/**
 * Parse directory path from full file path
 */
export function getDirectoryPath(filePath: string): string {
  const parts = filePath.split('/');
  parts.pop(); // Remove filename
  return parts.join('/');
}

/**
 * Check if path already exists in repository
 */
export async function pathExists(workspaceId: string, githubPath: string): Promise<boolean> {
  const existing = await prisma.document.findFirst({
    where: {
      workspaceId,
      githubPath,
    },
  });

  return !!existing;
}

/**
 * Generate unique path by appending number if needed
 */
export async function ensureUniquePath(workspaceId: string, basePath: string): Promise<string> {
  let path = basePath;
  let counter = 1;

  while (await pathExists(workspaceId, path)) {
    const ext = basePath.substring(basePath.lastIndexOf('.'));
    const base = basePath.substring(0, basePath.lastIndexOf('.'));
    path = `${base}-${counter}${ext}`;
    counter++;
  }

  return path;
}

/**
 * Bulk update paths for multiple documents
 */
export async function bulkUpdatePaths(
  documentIds: string[],
  config: PathMappingConfig = {}
): Promise<Map<string, string>> {
  const pathMap = new Map<string, string>();

  for (const docId of documentIds) {
    try {
      const path = await getDocumentGitHubPath(docId, config);
      pathMap.set(docId, path);
    } catch (error) {
      console.error(`Failed to generate path for document ${docId}:`, error);
    }
  }

  return pathMap;
}

/**
 * Get all documents in workspace without GitHub paths
 */
export async function getUnmappedDocuments(workspaceId: string) {
  return prisma.document.findMany({
    where: {
      workspaceId,
      githubPath: null,
    },
    select: {
      id: true,
      title: true,
      type: true,
    },
  });
}
